### ISSUE TITLE
Wavelets package

### ISSUE THREAD

**Issue by simonster** [JuliaDSP/Roadmap#1]
Per previous discussion, in JuliaDSP/DSP.jl#50, it would be great to have a wavelets package (or packages) under the JuliaDSP umbrella. @tomaskrehlik and @gummif, what needs to be done to merge your code? I'm happy to put my continuous wavelet transform implementation into the joint package or a separate package (not sure how much overlap there will be; anyway, CWT seems much simpler than DWT) and adapt it to whatever API you guys decide on.

**Comment by gummif** [comment]
It looks like the things my module is missing which @tomaskrehlik has is the `modwt` (algorithme à trous), a few filter utilities and filter types (la and bl). The current API is such that the transform is determined by a wavelet type object

``` julia
# transform L levels with
y = fwt(x, wt, L)
x2 = iwt(y, wt, L)
y = dwt!(x, wt, L, true)  # inplace forward
x2 = dwt!(y, x, wt, L, false)  # out of place inverse
y = fwt(x, wt)  # full MRA
# currently implemented types
wt = POfilter("db4")  # periodic orthogonal filter
wt = POfilter("Daubechies", 4)
wt = GPLS("db4")  # general periodic lifting scheme
# future types?
wt = BOLS("db4")  # boundary orthogonal
wt = SBLS("db4")  # symmetric boundaries (reflective)
wt = MOPOfilter("db4")  # modwt (algorithme à trous)
```

**Comment by tomaskrehlik** [comment]
I think that one of the main downsides of merging mine would be the forced adoption of the GPL, because mine is only a port from R that was done under GPL. However, I recently reimplemented faster version of modwt (which is in the speedup branch that I can claim mine and probably put it under MIT license).
I was thinking a lot recently about approach that @gummif took to designing the package. It has obvious advantages in terms of performance which is not a real deal breaker in places where I come from, where we tend to look at various parts of time-series spectra where only few people are used to work with signal processing tools so we try to keep them simple. Maybe could we do something to make the terminology also close to people coming from [time-series background](http://staff.washington.edu/dbp/wmtsa.html)? Maybe it could be handled in some part of documentation...
So I would probably rather port the @gummif 's package and include the modwtNew from my package, that would be probably the clearest way. Introducing the rest of filters should not be a problem. Designing the MODWT filters is easy, they are just scaled original filters, so I think you don't actually need a separate type for that. BTW, I really dislike the name `POfilter` and would really vote for something including the word wavelet.

**Comment by gummif** [comment]
I don't know about the terminology differences but they could easily be explained in the (non-existent) docs.

The idea is that `POfilter("db4")` and `MOPOfilter("db4")`  would use exactly the same qmf filter, but different algorithms would called when using `fwt(x,wt)` depending on the type of wt. Yes, `POfilter` isn't the prettiest name. The filter constructors could be wrapped in a function and used like 
`wt = waveletfilter("db4")`

``` julia
function waveletfilter(s::String, t::String="PO")
    t=="PO" && return POfilter(s)
    (t=="MO" || t=="MOPO") && return MOPOfilter(s)
    error("unknown type")
end
```

**Comment by gummif** [comment]
I think my package is in a good condition to be put under JuliaDSP and missing functions by @tomaskrehlik could be adapted to the agreed on API.

**Comment by tomaskrehlik** [comment]
@gummif I very much like what you did with the API, much prettier now! I will post a PR with MODWT and MODWPT in some time. (Hopefully by the end of next week.) I will also try to add some more examples from the time-series so that we can put together some documentation.

**Comment by simonster** [comment]
@gummif Sorry for being a bottleneck here. I've given you admin access, so go ahead and move this to JuliaDSP whenever you feel like it.

**Comment by gummif** [comment]
OK thanks. It's up and running in https://github.com/JuliaDSP/Wavelets.jl and has been registered in metadata. Anyone is welcome to contribute.

**Comment by jfsantos** [comment]
Since we've already transferred the repo, let's close this and move all discussions to the package repo. Thanks everyone!
